baseURL = "https://peaceful-brown-1ee8cb.netlify.com/"
languageCode = "en-us"
title = "StuffFluffRough"
theme = "ananke"
pygmentsCodeFences = true
pygmentsStyle = "rainbow_dash"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
